### ISSUE TITLE
Some usebility improvments for big graphs

### ISSUE THREAD

**Issue by Fox32** [kevmoo/pubviz#10]
I currently have quite a big dependcy graph in an application. I have so many edges, version constraints and packages that some parts are very hard to read. Especially when many edges cross each other.
It would be nice if one could click on a package and highlight all incomming and outgoing edges and their constraints.

However I don't know if the current graph library support something like this.

**Comment by kevmoo** [comment]
Yeah, we're limited by the GraphViz JS I'm using.

If you find something that does a better job, I'd love to migrate.

**Comment by kevmoo** [comment]
@Fox32 If you're bored, take a look at https://github.com/cpettitt/dagre

It might give us a bit more flexibility

**Comment by Fox32** [comment]
Nice work, it's the way I wished it. Makes working with it much faster. Can be closed from my side.

**Comment by kevmoo** [comment]
@Fox32 is happy. I'm happy.
