### ISSUE TITLE
Docs: explain how to convert dot output to other formats

### ISSUE THREAD

**Issue by orestesgaolin** [kevmoo/pubviz#44]
Hey there! I was trying to figure out how to export pubviz dot data to some format like png or pdf and it took me some time to understand how to do it with [graphviz](https://graphviz.org/doc/info/output.html#d:dot).

Would you like me to add some short description in the readme how to handle pubviz output? If not then that's fine, but wanted to ask before creating a PR.

**Comment by kevmoo** [comment]
If you want to take a stab at a PR, I'd happily review! I'm busy. 😄
